rewritten from functions to bin files

diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -5,26 +5,26 @@
 # Note: .dmg/hdiutil is macOS-specific.
 #
 # credit: http://nparikh.org/notes/zshrc.txt
-extract () {
-    if [ -f $1 ]; then
-        case $1 in
-            *.tar.bz2)  tar -jxvf $1                        ;;
-            *.tar.gz)   tar -zxvf $1                        ;;
-            *.bz2)      bunzip2 $1                          ;;
-            *.dmg)      hdiutil mount $1                    ;;
-            *.gz)       gunzip $1                           ;;
-            *.tar)      tar -xvf $1                         ;;
-            *.tbz2)     tar -jxvf $1                        ;;
-            *.tgz)      tar -zxvf $1                        ;;
-            *.zip)      unzip $1                            ;;
-            *.ZIP)      unzip $1                            ;;
-            *.pax)      cat $1 | pax -r                     ;;
-            *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
-            *.rar)      unrar x $1                          ;;
-            *.Z)        uncompress $1                       ;;
-            *)          echo "'$1' cannot be extracted/mounted via extract()" ;;
-        esac
-    else
-        echo "'$1' is not a valid file"
-    fi
-}
+
+[[ $# -eq 0 ]] && echo "Missing argument for extract" && exit 1
+[ ! -f $1 ] && echo "$1 is not a valid file" && exit 1
+
+case $1 in
+    *.tar.bz2)  tar -jxvf $1                        ;;
+    *.tar.gz)   tar -zxvf $1                        ;;
+    *.bz2)      bunzip2 $1                          ;;
+    *.dmg)      hdiutil mount $1                    ;;
+    *.gz)       gunzip $1                           ;;
+    *.tar)      tar -xvf $1                         ;;
+    *.tbz2)     tar -jxvf $1                        ;;
+    *.tgz)      tar -zxvf $1                        ;;
+    *.zip)      unzip $1                            ;;
+    *.ZIP)      unzip $1                            ;;
+    *.pax)      cat $1 | pax -r                     ;;
+    *.pax.Z)    uncompress $1 --stdout | pax -r     ;;
+    *.rar)      unrar x $1                          ;;
+    *.Z)        uncompress $1                       ;;
+    *)          echo "'$1' cannot be extracted/mounted via extract" && exit 1;;
+esac
+
+exit 0;
